version: '3.8'
services:
  database:
    image: mariadb:10.5
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ultradindb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8082:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8307:80"

volumes:
  db_data:
