# config/packages/nelmio_cors.yaml

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:8081']  # Frontend origin
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':  # Apply CORS settings to all routes
            allow_origin: ['http://localhost:8081']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
