security:
    # Hashage des mots de passe pour les utilisateurs authentifiés
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs (recharge des utilisateurs à partir de la base de données)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls Configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
  

        # Route de connexion pour les utilisateurs (login via JSON)
        login:
            pattern: ^/login
            stateless: true
            json_login: 
                check_path: /login
                username_path: email
                password_path: password

        # Firewall pour toutes les autres routes
        api:
            pattern: ^/
            stateless: true
            provider: app_user_provider
            jwt: ~

    # Contrôle d'accès pour sécuriser les routes
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

         


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 12
