version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      DATABASE_URL: mysql://root:docker1234@mysql:3306/ultradindb
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - cache_data:/var/www/html/var/cache
    depends_on:
      - mysql
    expose:
      - "9000"  # Expose PHP-FPM pour le service NGINX interne

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8000:80"  # Expose NGINX pour le navigateur
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: docker1234
      MYSQL_DATABASE: ultradindb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "8306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8307:80"

volumes:
  mysql_data:
  cache_data:
