# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true     
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Command\FetchExchangeRatesCommand:
        tags: ['console.command']
    Prometheus\Storage\InMemory: ~
    Prometheus\CollectorRegistry:
        arguments: ['@Prometheus\Storage\InMemory']
        shared: true
    App\Middleware\PrometheusMiddleware:
        arguments: ['@Prometheus\CollectorRegistry']
        tags: ['kernel.event_subscriber']
    App\Services\AzureBlobService:
       autowire: true
       arguments:
            $connectionString: '%env(AZURE_STORAGE_CONNECTION_STRING)%'



