name: Symfony

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env.test.local
        run: |
          ls
          pwd
          cd ultradinapp
          php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ultradinapp/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('ultradinapp/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: |
          cd ultradinapp
          composer install --no-interaction --no-progress --prefer-dist

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.4'
          mongodb-port: 27017

      - name: Migrate Database
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          cd ultradinapp
          mkdir -p data
          php bin/console doctrine:schema:create --no-interaction --env=test

      - name: Run Tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          cd ultradinapp
          vendor/bin/phpunit
